---
version: '0.2'

import: [ cspell.user.config.yaml ]

ignorePaths: []

dictionaryDefinitions: []
dictionaries:
  - en_US
  - softwareTerms
  - bash

words:
  - allowlist
  - backpressure
  - cooldown
  - debuggee
  - foldable
  - foldables
  - keepalive
  - lockscreen
  - recognised
  - unrecognised
  - unrequested
  - unsanitized
  - worktree
  - worktrees

ignoreWords:
  # names
  - georg
  - lauterbach
  - georglauterbach

  # Rust
  - clippy
  - lldb
  - rustc
  - rustdoc
  - rustup

  # Shell
  - pipefail
  - shopt
  - errexit

  # Python
  - pyproject
  - pytest
  - ruff
  - SCRIPTDIR

  # Acronyms
  - PKCS11

  # Tooling
  - containerfile
  - Containerfiles
  - endfor
  - envops
  - justfile
  - lstrip
  - nodev
  - nosuid
  - pathlib
  - shellcheck
  - shfmt
  - splitlines
  - startswith
  - strftime
  - tmpfs
  - trixie
  - zizmor
